// <auto-generated />
namespace LocalEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MaxLengthOfNamesAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaxLengthOfNamesAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202403280644418_MaxLengthOfNamesAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
